from typing import List, Dict
from models import Tank, Country, Product, AllocationRequest, AllocationResult

ISO_TANKS = [
    Tank(id="T11-24K", label="T11 — 24,000 L", size=24000, tare=3650, maxGross=36000, notes="24,000L · T11 rated · food & industrial grade"),
    Tank(id="T11-25K", label="T11 — 25,000 L", size=25000, tare=3750, maxGross=36000, notes="25,000L · T11 rated · food & industrial grade"),
    Tank(id="T11-26K", label="T11 — 26,000 L", size=26000, tare=3850, maxGross=36000, notes="26,000L · T11 rated · food & industrial grade"),
]

COUNTRY_GVW = {
    "Argentina": Country(name="Argentina", kg=36000, note="Tank structural maximum"),
    "Australia": Country(name="Australia", kg=26000, note="Australian road limit on standard B-double chassis"),
    "Austria": Country(name="Austria", kg=36000, note="Tank structural maximum"),
    "Bangladesh": Country(name="Bangladesh", kg=24000, note="Bangladesh road transport limit"),
    "Belgium": Country(name="Belgium", kg=36000, note="Tank structural maximum"),
    "Brazil": Country(name="Brazil", kg=36000, note="Tank structural maximum"),
    "Canada": Country(name="Canada", kg=23995, note="Canadian national highway limit — 23,995 kg gross (incl. tare)"),
    "Chile": Country(name="Chile", kg=36000, note="Tank structural maximum"),
    "China": Country(name="China", kg=30000, note="China GB1589 gross limit for 6-axle semi-trailer (tank)"),
    "Colombia": Country(name="Colombia", kg=36000, note="Tank structural maximum"),
    "Denmark": Country(name="Denmark", kg=36000, note="Tank structural maximum"),
    "Egypt": Country(name="Egypt", kg=36000, note="Tank structural maximum"),
    "Finland": Country(name="Finland", kg=36000, note="Tank structural maximum"),
    "France": Country(name="France", kg=36000, note="Tank structural maximum"),
    "Germany": Country(name="Germany", kg=36000, note="Tank structural maximum"),
    "Greece": Country(name="Greece", kg=36000, note="Tank structural maximum"),
    "Hong Kong": Country(name="Hong Kong", kg=36000, note="Tank structural maximum"),
    "India": Country(name="India", kg=30000, note="India MV Act gross limit for articulated vehicle"),
    "Indonesia": Country(name="Indonesia", kg=36000, note="Tank structural maximum"),
    "Ireland": Country(name="Ireland", kg=36000, note="Tank structural maximum"),
    "Israel": Country(name="Israel", kg=36000, note="Tank structural maximum"),
    "Italy": Country(name="Italy", kg=36000, note="Tank structural maximum"),
    "Japan": Country(name="Japan", kg=28000, note="Japan road vehicle law gross limit for semi-trailer"),
    "Jordan": Country(name="Jordan", kg=36000, note="Tank structural maximum"),
    "Kenya": Country(name="Kenya", kg=36000, note="Tank structural maximum"),
    "Malaysia": Country(name="Malaysia", kg=36000, note="Tank structural maximum"),
    "Mexico": Country(name="Mexico", kg=24000, note="Mexican federal highway limit (SCT NOM-012)"),
    "Morocco": Country(name="Morocco", kg=36000, note="Tank structural maximum"),
    "Myanmar": Country(name="Myanmar", kg=21000, note="Myanmar road limit (lower infrastructure standard)"),
    "Netherlands": Country(name="Netherlands", kg=36000, note="Tank structural maximum"),
    "New Zealand": Country(name="New Zealand", kg=26000, note="NZ road limit on standard articulated combination"),
    "Nigeria": Country(name="Nigeria", kg=36000, note="Tank structural maximum"),
    "Norway": Country(name="Norway", kg=36000, note="Tank structural maximum"),
    "Oman": Country(name="Oman", kg=36000, note="Tank structural maximum"),
    "Pakistan": Country(name="Pakistan", kg=30000, note="Pakistan NHA gross vehicle weight limit"),
    "Peru": Country(name="Peru", kg=36000, note="Tank structural maximum"),
    "Philippines": Country(name="Philippines", kg=36000, note="Tank structural maximum"),
    "Poland": Country(name="Poland", kg=36000, note="Tank structural maximum"),
    "Portugal": Country(name="Portugal", kg=36000, note="Tank structural maximum"),
    "Qatar": Country(name="Qatar", kg=36000, note="Tank structural maximum"),
    "Saudi Arabia": Country(name="Saudi Arabia", kg=36000, note="Tank structural maximum"),
    "Singapore": Country(name="Singapore", kg=36000, note="Tank structural maximum"),
    "South Africa": Country(name="South Africa", kg=36000, note="Tank structural maximum"),
    "South Korea": Country(name="South Korea", kg=30000, note="Korea road limit for semi-trailer combination"),
    "Spain": Country(name="Spain", kg=36000, note="Tank structural maximum"),
    "Sri Lanka": Country(name="Sri Lanka", kg=24000, note="Sri Lanka road transport gross limit"),
    "Sweden": Country(name="Sweden", kg=36000, note="Tank structural maximum"),
    "Switzerland": Country(name="Switzerland", kg=36000, note="Tank structural maximum"),
    "Taiwan": Country(name="Taiwan", kg=28000, note="Taiwan highway vehicle weight regulation"),
    "Thailand": Country(name="Thailand", kg=36000, note="Tank structural maximum"),
    "Turkey": Country(name="Turkey", kg=36000, note="Tank structural maximum"),
    "UAE": Country(name="UAE", kg=36000, note="Tank structural maximum"),
    "Ukraine": Country(name="Ukraine", kg=36000, note="Tank structural maximum"),
    "United Kingdom": Country(name="United Kingdom", kg=36000, note="Tank structural maximum"),
    "USA": Country(name="USA", kg=23995, note="US federal highway limit — 23,995 kg gross (incl. tare)"),
    "Vietnam": Country(name="Vietnam", kg=36000, note="Tank structural maximum"),
    "Zambia": Country(name="Zambia", kg=36000, note="Tank structural maximum"),
}

COMMON_PRODUCTS = [
    Product(name="Methanol", sg=0.791, dg=True, un="UN1230", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Ethanol", sg=0.789, dg=True, un="UN1170", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Isopropanol (IPA)", sg=0.786, dg=True, un="UN1219", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Toluene", sg=0.867, dg=True, un="UN1294", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Acetone", sg=0.791, dg=True, un="UN1090", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Ethyl Acetate", sg=0.897, dg=True, un="UN1173", pg="II", cls="3", minFill=80, maxFill=95),
    Product(name="Xylene", sg=0.864, dg=True, un="UN1307", pg="III", cls="3", minFill=80, maxFill=95),
    Product(name="Caustic Soda 50%", sg=1.525, dg=True, un="UN1824", pg="II", cls="8", minFill=80, maxFill=95),
    Product(name="Hydrochloric Acid 32%", sg=1.159, dg=True, un="UN1789", pg="III", cls="8", minFill=80, maxFill=97),
    Product(name="Phosphoric Acid 85%", sg=1.685, dg=True, un="UN1805", pg="III", cls="8", minFill=80, maxFill=97),
    Product(name="Sulfuric Acid 98%", sg=1.84, dg=True, un="UN1830", pg="II", cls="8", minFill=80, maxFill=93),
    Product(name="Acetic Acid 80%", sg=1.064, dg=True, un="UN2790", pg="III", cls="8", minFill=80, maxFill=97),
    Product(name="Hydrogen Peroxide 50%", sg=1.196, dg=True, un="UN2014", pg="II", cls="5.1", minFill=80, maxFill=90),
    Product(name="Formaldehyde 37%", sg=1.09, dg=True, un="UN1198", pg="III", cls="3", minFill=80, maxFill=97),
    Product(name="Crude Palm Oil (CPO)", sg=0.891, dg=False, minFill=85, maxFill=98),
    Product(name="Refined Palm Olein", sg=0.9, dg=False, minFill=85, maxFill=98),
    Product(name="Refined Palm Stearin", sg=0.904, dg=False, minFill=85, maxFill=98),
    Product(name="Soybean Oil (RBD)", sg=0.919, dg=False, minFill=85, maxFill=98),
    Product(name="Sunflower Oil", sg=0.92, dg=False, minFill=85, maxFill=98),
    Product(name="Canola Oil", sg=0.915, dg=False, minFill=85, maxFill=98),
    Product(name="Coconut Oil (RBD)", sg=0.912, dg=False, minFill=85, maxFill=98),
    Product(name="Glycerin 99.5%", sg=1.261, dg=False, minFill=85, maxFill=98),
    Product(name="Propylene Glycol", sg=1.036, dg=False, minFill=85, maxFill=98),
    Product(name="Ethylene Glycol", sg=1.113, dg=False, minFill=85, maxFill=98),
    Product(name="Latex (Natural Rubber)", sg=0.96, dg=False, minFill=85, maxFill=98),
    Product(name="Molasses", sg=1.4, dg=False, minFill=85, maxFill=97),
    Product(name="Corn Syrup", sg=1.38, dg=False, minFill=85, maxFill=97),
    Product(name="Water / Aqueous Sol.", sg=1.0, dg=False, minFill=85, maxFill=98),
    Product(name="Liquid Fertilizer (UAN)", sg=1.28, dg=False, minFill=85, maxFill=97),
]
