import type { Tank, Product, Country } from './types';

/** Static fleet data — mirrors backend/data.py ISO_TANKS */
export const STATIC_FLEET: Tank[] = [
  { id: 'T11-24K', label: 'T11 — 24,000 L', size: 24000, tare: 3650, maxGross: 36000, notes: '24,000L · T11 rated · food & industrial grade' },
  { id: 'T11-25K', label: 'T11 — 25,000 L', size: 25000, tare: 3750, maxGross: 36000, notes: '25,000L · T11 rated · food & industrial grade' },
  { id: 'T11-26K', label: 'T11 — 26,000 L', size: 26000, tare: 3850, maxGross: 36000, notes: '26,000L · T11 rated · food & industrial grade' },
];

/** Static country GVM data — mirrors backend/data.py COUNTRY_GVW */
export const STATIC_COUNTRIES: Country[] = [
  { name: 'Argentina', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Australia', kg: 26000, note: 'Australian road limit on standard B-double chassis' },
  { name: 'Austria', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Bangladesh', kg: 24000, note: 'Bangladesh road transport limit' },
  { name: 'Belgium', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Brazil', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Canada', kg: 23995, note: 'Canadian national highway limit — 23,995 kg gross (incl. tare)' },
  { name: 'Chile', kg: 36000, note: 'Tank structural maximum' },
  { name: 'China', kg: 30000, note: 'China GB1589 gross limit for 6-axle semi-trailer (tank)' },
  { name: 'Colombia', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Denmark', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Egypt', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Finland', kg: 36000, note: 'Tank structural maximum' },
  { name: 'France', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Germany', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Greece', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Hong Kong', kg: 36000, note: 'Tank structural maximum' },
  { name: 'India', kg: 30000, note: 'India MV Act gross limit for articulated vehicle' },
  { name: 'Indonesia', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Ireland', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Israel', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Italy', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Japan', kg: 28000, note: 'Japan road vehicle law gross limit for semi-trailer' },
  { name: 'Jordan', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Kenya', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Malaysia', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Mexico', kg: 24000, note: 'Mexican federal highway limit (SCT NOM-012)' },
  { name: 'Morocco', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Myanmar', kg: 21000, note: 'Myanmar road limit (lower infrastructure standard)' },
  { name: 'Netherlands', kg: 36000, note: 'Tank structural maximum' },
  { name: 'New Zealand', kg: 26000, note: 'NZ road limit on standard articulated combination' },
  { name: 'Nigeria', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Norway', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Oman', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Pakistan', kg: 30000, note: 'Pakistan NHA gross vehicle weight limit' },
  { name: 'Peru', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Philippines', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Poland', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Portugal', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Qatar', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Saudi Arabia', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Singapore', kg: 36000, note: 'Tank structural maximum' },
  { name: 'South Africa', kg: 36000, note: 'Tank structural maximum' },
  { name: 'South Korea', kg: 30000, note: 'Korea road limit for semi-trailer combination' },
  { name: 'Spain', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Sri Lanka', kg: 24000, note: 'Sri Lanka road transport gross limit' },
  { name: 'Sweden', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Switzerland', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Taiwan', kg: 28000, note: 'Taiwan highway vehicle weight regulation' },
  { name: 'Thailand', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Turkey', kg: 36000, note: 'Tank structural maximum' },
  { name: 'UAE', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Ukraine', kg: 36000, note: 'Tank structural maximum' },
  { name: 'United Kingdom', kg: 36000, note: 'Tank structural maximum' },
  { name: 'USA', kg: 23995, note: 'US federal highway limit — 23,995 kg gross (incl. tare)' },
  { name: 'Vietnam', kg: 36000, note: 'Tank structural maximum' },
  { name: 'Zambia', kg: 36000, note: 'Tank structural maximum' },
];

/** Static product library — mirrors backend/data.py COMMON_PRODUCTS */
export const STATIC_PRODUCTS: Product[] = [
  { name: 'Methanol', sg: 0.791, dg: true, un: 'UN1230', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Ethanol', sg: 0.789, dg: true, un: 'UN1170', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Isopropanol (IPA)', sg: 0.786, dg: true, un: 'UN1219', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Toluene', sg: 0.867, dg: true, un: 'UN1294', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Acetone', sg: 0.791, dg: true, un: 'UN1090', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Ethyl Acetate', sg: 0.897, dg: true, un: 'UN1173', pg: 'II', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Xylene', sg: 0.864, dg: true, un: 'UN1307', pg: 'III', cls: '3', minFill: 80, maxFill: 95 },
  { name: 'Caustic Soda 50%', sg: 1.525, dg: true, un: 'UN1824', pg: 'II', cls: '8', minFill: 80, maxFill: 95 },
  { name: 'Hydrochloric Acid 32%', sg: 1.159, dg: true, un: 'UN1789', pg: 'III', cls: '8', minFill: 80, maxFill: 97 },
  { name: 'Phosphoric Acid 85%', sg: 1.685, dg: true, un: 'UN1805', pg: 'III', cls: '8', minFill: 80, maxFill: 97 },
  { name: 'Sulfuric Acid 98%', sg: 1.84, dg: true, un: 'UN1830', pg: 'II', cls: '8', minFill: 80, maxFill: 93 },
  { name: 'Acetic Acid 80%', sg: 1.064, dg: true, un: 'UN2790', pg: 'III', cls: '8', minFill: 80, maxFill: 97 },
  { name: 'Hydrogen Peroxide 50%', sg: 1.196, dg: true, un: 'UN2014', pg: 'II', cls: '5.1', minFill: 80, maxFill: 90 },
  { name: 'Formaldehyde 37%', sg: 1.09, dg: true, un: 'UN1198', pg: 'III', cls: '3', minFill: 80, maxFill: 97 },
  { name: 'Crude Palm Oil (CPO)', sg: 0.891, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Refined Palm Olein', sg: 0.9, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Refined Palm Stearin', sg: 0.904, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Soybean Oil (RBD)', sg: 0.919, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Sunflower Oil', sg: 0.92, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Canola Oil', sg: 0.915, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Coconut Oil (RBD)', sg: 0.912, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Glycerin 99.5%', sg: 1.261, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Propylene Glycol', sg: 1.036, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Ethylene Glycol', sg: 1.113, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Latex (Natural Rubber)', sg: 0.96, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Molasses', sg: 1.4, dg: false, minFill: 85, maxFill: 97 },
  { name: 'Corn Syrup', sg: 1.38, dg: false, minFill: 85, maxFill: 97 },
  { name: 'Water / Aqueous Sol.', sg: 1.0, dg: false, minFill: 85, maxFill: 98 },
  { name: 'Liquid Fertilizer (UAN)', sg: 1.28, dg: false, minFill: 85, maxFill: 97 },
];
